export type vec3 = [number, number, number];
export type vec4 = [number, number, number, number];
export type mat3 = [vec3, vec3, vec3];
export type mat4 = [vec4, vec4, vec4, vec4];
export declare function length(vec: number[]): number;
export declare function normalize(vec: number[]): number[];
export declare function mvmul(lhs: number[][], rhs: number[]): number[];
export declare function mmul(lhs: number[][], rhs: number[][]): number[][];
export declare function identity(size: number): number[][];
export declare function det3(mat: mat3): number;
export declare function inv3(mat: mat3): mat3;
export declare function quaternion_conj(q: vec4): vec4;
export declare function quaternion_mul(lhs: vec4, rhs: vec4): vec4;
export declare function quaternion_to_mat(q: vec4): mat3;
export declare function mat_to_quaternion(mat: mat3 | mat4): vec4;
export declare function GivensTransform(mat: number[][], row0: number, row1: number, angle: number): void;
export declare function Euler_to_mat(angles: [number, number, number], order?: string): mat3;
export declare function make_homogeneous(mat: mat3, translation: vec3): mat4;
export declare function flatten(mat: number[][]): number[];
